version: '2'
services:
  postgres:
    image: postgis/postgis:11-3.2
    hostname: postgres
    container_name: dbt_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

    ports:
      - "5432:5432"